global:
  sequence_length: 200
  embedding_size: 50
  num_classes: 2
  num_tasks: 16
  static: False
  rnn_hidden_size: 128
  mlp_hidden_size: 200
  dynamic: True
  use_attention: False
  attention_size: 50
  batch_size: 16
  learning_rate: 0.00001
  epochs: 10
  lamda: 0.0001

shared_model:
  num_layers: 1  
  
private_model:
  num_layers: 1
  
task:
 - apparel
 - baby
 - books
 - camera_photo
 - dvd
 - electronics
 - health_personal_care
 - imdb
 - kitchen_housewares
 - magazines
 - MR
 - music
 - software
 - sports_outdoors
 - toys_games
 - video

optimum_length:
 - 265
 - 446
 - 735
 - 566
 - 764
 - 503
 - 503
 - 802
 - 415
 - 246
 - 43
 - 447
 - 522
 - 327
 - 337
 - 340


